### ISSUE TITLE
Error when loading into Sublime Text 3

### ISSUE THREAD

**Issue by mhanberg** [tobiastimm/code-theme-converter#13]
I tried converting a couple vscode themes (https://github.com/sainnhe/forest-night-vscode and https://github.com/sdras/night-owl-vscode-theme), and neither of them work in Sublime Text 3.

Here is an image of the error I see
![image](https://user-images.githubusercontent.com/5523984/83344507-e318ab80-a2d5-11ea-9e3a-9add8196da49.png)

**Comment by tobiastimm** [comment]
Thank you for reporting! I will take a look

**Comment by tobiastimm** [comment]
@mhanberg Should be fixed with `1.0.2`

**Comment by mhanberg** [comment]
Confirmed to work, thanks!!!
