### ISSUE TITLE
List of issues for JetBrains

### ISSUE THREAD

**Issue by jef** [tobiastimm/code-theme-converter#14]
Do you mind creating a board or issues around JetBrains? That way contributors could see what's in progress or where help is needed?

**Comment by tobiastimm** [comment]
Yeah, I will create that soon! Want to finish my typescript rewrite first and then collect the remaining features and issues that need to be created.

**Comment by tobiastimm** [comment]
Short update from my side, still working on that. I don't have that much time right now, but will try to merge the PR within the next two weeks. So please stay tuned!

**Comment by tobiastimm** [comment]
I've added some issues for JetBrains and merged my latest changes into the master.
#17 is a blocker to make the conversion work.
After that tickets like #18 #22 #23 can follow

**Comment by jef** [comment]
Awesome! Thanks @tobiastimm
