### ISSUE TITLE
Only single theme is installed in case of multiple themes.

### ISSUE THREAD

**Issue by adipro7** [tobiastimm/code-theme-converter#15]
I tried to convert AposTheme which is only available for VS Code to Sublime Text Theme. Apos Theme has 4 colour schemes: Blue, Gray, Red and Green. When I tried the code converter on the following repo: [AposTheme](https://github.com/Apostolique/AposTheme), it only converted the last one which is the Red theme. I think it is because of the alphabetical order or an Overwriting Issue which can be solved by giving the file name a number. Thanks!

**Comment by tobiastimm** [comment]
Sry for the late reply! I will take a look! Thanks for reporting

**Comment by tobiastimm** [comment]
I have looked into that. I'm grabbing the name specified in the `theme.json.` IMO; this name should be equal to the theme's file-name or variant.
The theme you mentioned is overwriting that name within the `package.json.` 
If this use-case happens more often, I would consider changing that, but most themes specify the names correctly.
