### ISSUE TITLE
Unable to convert VSCode to sublime as-tm-theme

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [tobiastimm/code-theme-converter#33]
Trying to convert this Spacemacs theme to tmTheme. It says it succeeds but doesn't make a `tmTheme` file (does make sublime colorscheme though). I edit the library to make tmTheme default to true and it makes `tmTheme` file extension but is not tmTheme format.

```shell
code2subl https://github.com/cometeer/spacemacs-vscode.git --as-tm-theme
```

**Comment by tobiastimm** [comment]
I will try to take a look! thank you for reporting!

**Comment by RobinBoers** [comment]
I have the exact same problem here

**Comment by chtenb** [comment]
Same problem and same fix. However, the generated tm theme file is invalid, because at the start it inserts two `      <dict>
      <dict>` tags. Easy to fix by hand of course, but for automation purposes it should be fixed.

**Comment by chtenb** [comment]
PR incoming
