### ISSUE TITLE
Unable to convert VSCode to IDEA vscode-neon-vommit-theme

### ISSUE THREAD

**Issue by neonduplex** [tobiastimm/code-theme-converter#34]
Hi there,

I just installed your converter (macOs) and converting my favourite theme vscode-neon-vommit-theme ends up in a nearly empty .theme.json file in the _src_ directory.

```
{
  "name": "Neon Vommit",
  "dark": true,
  "editorScheme": "/themes/neonvommit.xml",
  "ui": {
    "*": {
      "background": "",
      "foreground": ""
    }
  }
}
```
Folders _META-INF_ and _themes_ are also empty.

Neon Vommit Theme: https://github.com/ghgofort/vscode-neon-vommit-theme.git

**Comment by tobiastimm** [comment]
The IntelliJ IDEA converter is not working atm. Mentioned within the README
