### ISSUE TITLE
NPM Package Not Found

### ISSUE THREAD

**Issue by SkylerStearns** [tobiastimm/code-theme-converter#7]
When attempting to install via `npm install --global --save code-theme-converter` per the README, the command fails due to the package not being found. When confirming on the NPM registry, I found that they also show that this package does not exist.

**Comment by tobiastimm** [comment]
@SkylerStearns yeah that's right. When I started the project, I wanted to publish it asap on npm. Unfortunately, I never did that. 
I will remove that line out of the readme. 
Atm, I'm rewriting the whole package in TypeScript, after that, I will publish it to npm for sure.
